name: Validate with hassfest

on:
  push:
    branches: [ "main", "ver*" ]
  pull_request:
    branches: [ "main", "ver*" ]

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"
